import { type SQLiteDatabase } from 'expo-sqlite';

import { type Album } from '../albums/types';
import { deleteImageFile } from '../images/imageStorage';
import { deleteAudioFile } from './audioStorage';
import {
  countTracksByArtist,
  deleteTrack,
  insertTrack,
  listTracksByAlbum,
  listTracksByArtist,
  setTrackAlbum,
  setTrackArtist,
  setTrackFavorite,
  setTrackImage,
  setTrackTitle,
} from './repository';
import { type Track } from './types';

/** Business logic for tracks — orchestrates the repository, never touches SQL directly from callers. */

export type NewTrackInput = {
  artistId: string;
  title: string;
  audioUri: string;
  /** Optional cover chosen at creation. Empty means the track inherits its album's or artist's. */
  imageUri?: string;
  durationSeconds: number;
};

export type CreateTrackResult = { ok: true; track: Track } | { ok: false; error: 'empty_title' };

export async function getTracksByArtist(db: SQLiteDatabase, artistId: string): Promise<Track[]> {
  return listTracksByArtist(db, artistId);
}

export async function getTracksByAlbum(db: SQLiteDatabase, albumId: string): Promise<Track[]> {
  return listTracksByAlbum(db, albumId);
}

export async function getTrackCountByArtist(db: SQLiteDatabase, artistId: string): Promise<number> {
  return countTracksByArtist(db, artistId);
}

/**
 * `trackId` is generated by the caller (useCreateTrack) rather than here, because the audio file must
 * be persisted under that same id (see audioStorage.ts) before this is called — generating it here
 * would produce a track row whose id doesn't match its already-copied audio file.
 */
export async function createTrack(db: SQLiteDatabase, trackId: string, input: NewTrackInput): Promise<CreateTrackResult> {
  const title = input.title.trim();
  if (title.length === 0) {
    return { ok: false, error: 'empty_title' };
  }

  const track: Track = {
    id: trackId,
    title,
    artistId: input.artistId,
    albumId: null,
    audioUri: input.audioUri,
    imageUri: input.imageUri ?? '',
    durationSeconds: input.durationSeconds,
    isFavorite: false,
    createdAt: Date.now(),
  };

  await insertTrack(db, track);
  return { ok: true, track };
}

export async function toggleTrackFavorite(db: SQLiteDatabase, track: Track): Promise<void> {
  await setTrackFavorite(db, track.id, !track.isFavorite);
}

export async function changeTrackArtist(db: SQLiteDatabase, trackId: string, artistId: string): Promise<void> {
  await setTrackArtist(db, trackId, artistId);
}

export type ChangeTrackAlbumResult = { ok: true } | { ok: false; error: 'album_belongs_to_another_artist' };

/**
 * Moves a track into an album, or out of any album when `albumId` is null. Rejects an album owned by
 * a different artist — every track in an album must share that album's artist.
 */
export async function changeTrackAlbum(
  db: SQLiteDatabase,
  track: Track,
  album: Album | null
): Promise<ChangeTrackAlbumResult> {
  if (album && album.artistId !== track.artistId) {
    return { ok: false, error: 'album_belongs_to_another_artist' };
  }
  await setTrackAlbum(db, track.id, album?.id ?? null);
  return { ok: true };
}

export type RenameTrackResult = { ok: true } | { ok: false; error: 'empty_title' };

export async function renameTrack(db: SQLiteDatabase, trackId: string, rawTitle: string): Promise<RenameTrackResult> {
  const title = rawTitle.trim();
  if (title.length === 0) {
    return { ok: false, error: 'empty_title' };
  }
  await setTrackTitle(db, trackId, title);
  return { ok: true };
}

/** Replaces the track's cover, deleting the previous file so old images don't pile up on disk. */
export async function changeTrackImage(db: SQLiteDatabase, track: Track, imageUri: string): Promise<void> {
  await setTrackImage(db, track.id, imageUri);
  if (track.imageUri.length > 0 && track.imageUri !== imageUri) {
    deleteImageFile(track.imageUri);
  }
}

export async function removeTrack(db: SQLiteDatabase, track: Track): Promise<void> {
  await deleteTrack(db, track.id);
  deleteAudioFile(track.audioUri);
  deleteImageFile(track.imageUri);
}
