import { type SQLiteDatabase } from 'expo-sqlite';

import { deleteAudioFile } from './audioStorage';
import {
  countTracksByArtist,
  deleteTrack,
  insertTrack,
  listTracksByArtist,
  setTrackArtist,
  setTrackFavorite,
} from './repository';
import { type Track } from './types';

/** Business logic for tracks — orchestrates the repository, never touches SQL directly from callers. */

export type NewTrackInput = {
  artistId: string;
  title: string;
  audioUri: string;
  durationSeconds: number;
};

export type CreateTrackResult = { ok: true; track: Track } | { ok: false; error: 'empty_title' };

export async function getTracksByArtist(db: SQLiteDatabase, artistId: string): Promise<Track[]> {
  return listTracksByArtist(db, artistId);
}

export async function getTrackCountByArtist(db: SQLiteDatabase, artistId: string): Promise<number> {
  return countTracksByArtist(db, artistId);
}

/**
 * `trackId` is generated by the caller (useCreateTrack) rather than here, because the audio file must
 * be persisted under that same id (see audioStorage.ts) before this is called — generating it here
 * would produce a track row whose id doesn't match its already-copied audio file.
 */
export async function createTrack(db: SQLiteDatabase, trackId: string, input: NewTrackInput): Promise<CreateTrackResult> {
  const title = input.title.trim();
  if (title.length === 0) {
    return { ok: false, error: 'empty_title' };
  }

  const track: Track = {
    id: trackId,
    title,
    artistId: input.artistId,
    audioUri: input.audioUri,
    durationSeconds: input.durationSeconds,
    isFavorite: false,
    createdAt: Date.now(),
  };

  await insertTrack(db, track);
  return { ok: true, track };
}

export async function toggleTrackFavorite(db: SQLiteDatabase, track: Track): Promise<void> {
  await setTrackFavorite(db, track.id, !track.isFavorite);
}

export async function changeTrackArtist(db: SQLiteDatabase, trackId: string, artistId: string): Promise<void> {
  await setTrackArtist(db, trackId, artistId);
}

export async function removeTrack(db: SQLiteDatabase, track: Track): Promise<void> {
  await deleteTrack(db, track.id);
  deleteAudioFile(track.audioUri);
}
